all: LinearTrail2 OneActiveSbox_LinearTrail
LinearTrail2:
	gcc -Wall -O3 -lm LinearTrail2.c -o LinearTrail2
OneActiveSbox_LinearTrail:
	gcc -Wall -O3 -lm OneActiveSbox_LinearTrail.c -o OneActiveSbox_LinearTrail
clean:
	\rm -f LinearTrail2 OneActiveSbox_LinearTrail
