#! /bin/bash

if [ $# -lt 1 ] ; then
    echo usage: $0 hash_name [round_number] >&2
    exit 1
fi

HASH=$1
R=${2:-0}

while read line ; do
    MSG="$MSG$line
"
done

cat <<EOF | magma -b "r:=$R" utils.m $HASH/main.m
printbits(hash(stringtobits("$MSG")));
EOF
